### ISSUE TITLE
Host Dev in AWS

### ISSUE THREAD

**Issue by apklinker** [sourceallies/hacker-rank-queue#9]
- Dev and Prod environments
- Easy way to publish during development (like heroku's `yarn deploy`)

Application is already dockerized, and the plan is to put it in a new ECS Fargate

### Tasks

- [x] Deploy stack to dev (#9)
- [x] Setup static url for dev
- [x] Label existing slack app as the dev app
- [x] Write deploy application script for development

**Comment by apklinker** [comment]
ECS in dev makes deployments super slow (> 5m) when we want it to be fast (< 10s)... So the stack Skiff, Talen, and I worked on is perfect for prod, but not for dev :/

**Comment by aklinker1** [comment]
Gonna reduce the scope of this and put off the production work

**Comment by apklinker** [comment]
Gonna reduce the scope of this and put off the production work

**Comment by apklinker** [comment]
See #15
